apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mywebapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Swistek92/infrastructure'
    targetRevision: main
    path: environments/dev
    helm:
      valueFiles:
        - mywebapp-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
