metadata:
  name: strimzi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # najpierw operator
spec:
  destination:
    namespace: kafka
  source:
    repoURL: https://github.com/strimzi/strimzi-kafka-operator.git
    targetRevision: 0.41.0
    path: install/cluster-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
