apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.42.0
    helm:
      values: |
        watchAnyNamespace: false
        watchNamespaces:
          - kafka
        resources:
          requests:
            memory: 1Gi
            cpu: "1"
          limits:
            memory: 10Gi
            cpu: "4"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
