apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.41.0     # dopasuj do potrzeb; ważne: wersja istniejąca w repo Helm
    helm:
      releaseName: strimzi-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
