apiGateway:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/api-gateway
    tag: latest
    pullPolicy: Always
  env:
    NODE_ENV: "production"
    KAFKA_BROKER: "dev-kafka-bootstrap.kafka.svc:9092"
    PRODUCTS_GRPC_URL: "products-ms.app.svc:50051"
  service:
    type: ClusterIP
    port: 3000
# ------------------------------------------------------------------
notification:
  name: notification-ms
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/notification-microservice
    tag: latest
    pullPolicy: IfNotPresent
  env:
    KAFKA_BROKER: "dev-kafka-bootstrap.kafka:9092"
    NODE_ENV: "production"
  service:
    type: ClusterIP
    port: 3000
# ------------------------------------------------------------------
order:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/order-microservice
    tag: latest
    pullPolicy: IfNotPresent
  env:
    KAFKA_BROKER: "dev-kafka-bootstrap.kafka:9092"
    NODE_ENV: "production"
  service:
    type: ClusterIP
    port: 3000
  probes:
    enabled: true
    initialDelaySeconds: 10
    livenessInitialDelaySeconds: 30
# ------------------------------------------------------------------
payment:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/payment-microservice
    tag: latest
    pullPolicy: IfNotPresent
  env:
    KAFKA_BROKER: "dev-kafka-bootstrap.kafka:9092"
    NODE_ENV: "production"
  service:
    type: ClusterIP
    port: 3000
  probes:
    enabled: true
    initialDelaySeconds: 10
    livenessInitialDelaySeconds: 30
# ------------------------------------------------------------------
products:
  replicas: 1
  containerPort: 50051
  image:
    repository: swistek/products-microservice
    tag: latest
    pullPolicy: Always
  env:
    NODE_ENV: "production"
  service:
    type: ClusterIP
    port: 50051
  probes:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 20
# ----------------------------------------------------------------