# values.yaml
global:
  imagePullSecrets:
    - dockerhub-cred

# ---- wspólne: adres brokera Strimzi ----
kafka:
  # jeśli Strimzi jest w ns "kafka" i klaster nazywa się "my-cluster":
  bootstrap: "my-cluster-kafka-bootstrap.kafka:9092"
  # FQDN też zadziała: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  # Dla TLS zwykle użyj 9093 i dodatkowych sekretnych zmiennych/Cert:
  # bootstrap: "my-cluster-kafka-bootstrap.kafka:9093"
  # tls: true

apiGateway:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/api-gateway
    tag: latest
    pullPolicy: Always
  env:
    NODE_ENV: "production"
    KAFKA_BROKER: "my-cluster-kafka-bootstrap.kafka:9092"
    PRODUCTS_GRPC_URL: "mywebapp-webapp-products:50051"
  service:
    type: ClusterIP
    port: 3000

notification:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/notification-microservice
    tag: latest
    pullPolicy: IfNotPresent
  env:
    NODE_ENV: "production"
    KAFKA_BROKER: "my-cluster-kafka-bootstrap.kafka:9092"
  service:
    type: ClusterIP
    port: 3000

order:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/order-microservice
    tag: latest
    pullPolicy: IfNotPresent
  env:
    NODE_ENV: "production"
    KAFKA_BROKER: "my-cluster-kafka-bootstrap.kafka:9092"
  service:
    type: ClusterIP
    port: 3000
  probes:
    enabled: true
    initialDelaySeconds: 10
    livenessInitialDelaySeconds: 30

payment:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/payment-microservice
    tag: latest
    pullPolicy: IfNotPresent
  env:
    NODE_ENV: "production"
    KAFKA_BROKER: "my-cluster-kafka-bootstrap.kafka:9092"
  service:
    type: ClusterIP
    port: 3000
  probes:
    enabled: true
    initialDelaySeconds: 10
    livenessInitialDelaySeconds: 30

products:
  replicas: 1
  containerPort: 50051
  image:
    repository: swistek/products-microservice
    tag: latest
    pullPolicy: Always
  env:
    NODE_ENV: "production"
  service:
    type: ClusterIP
    port: 50051
  probes:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 20

# Kafka z chartu wyłączona – używasz Strimzi
kafkaBuiltin:
  enabled: false

zookeeper:
  enabled: false
