# ZMIEN TO jeśli Twój Kafka CR/namespace mają inne nazwy
kafka:
  bootstrapServers: "my-cluster-kafka-bootstrap.kafka:9092"

global:
  imagePullSecrets:
    - dockerhub-cred

# ===== Wspólne ENV dla wszystkich podów (prod+NestJS microservices) =====
commonEnv:
  NODE_ENV: "production"
  # dla klienta używającego jednej wartości:
  KAFKA_BROKER: "{{ .Values.kafka.bootstrapServers }}"
  # dla NestJS ServerKafka / kafkajs, które oczekują listy brokerów:
  KAFKA_BROKERS: "{{ .Values.kafka.bootstrapServers }}"
  # jeśli gdzieś kod rozbija host/port osobno – zostawiamy też to:
  KAFKA_HOST: "{{ (splitList \":\" .Values.kafka.bootstrapServers)._0 }}"
  KAFKA_PORT: "{{ (splitList \":\" .Values.kafka.bootstrapServers)._1 | default \"9092\" }}"
  # wyciszenie ostrzeżenia kafkajs
  KAFKAJS_NO_PARTITIONER_WARNING: "1"

apiGateway:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/api-gateway
    tag: latest
    pullPolicy: Always
  env:
    # specyficzne tylko dla tej usługi
    PRODUCTS_GRPC_URL: "mywebapp-webapp-products:50051"
  service:
    type: ClusterIP
    port: 3000

notification:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/notification-microservice
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000

order:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/order-microservice
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  probes:
    enabled: true
    initialDelaySeconds: 10
    livenessInitialDelaySeconds: 30

payment:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/payment-microservice
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  probes:
    enabled: true
    initialDelaySeconds: 10
    livenessInitialDelaySeconds: 30

products:
  replicas: 1
  containerPort: 50051
  image:
    repository: swistek/products-microservice
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 50051
  probes:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 20

# W tym charcie Kafka/ZK wyłączone – używasz Strimzi
kafkaChart:
  enabled: false
zookeeper:
  enabled: false
