global:
  imagePullSecrets:
    - dockerhub-cred

apiGateway:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/api-gateway
    tag: latest
    pullPolicy: Always
  env:
    NODE_ENV: "production"
    KAFKA_BROKER: "mywebapp-kafka:9092"
    PRODUCTS_GRPC_URL: "mywebapp-webapp-products:50051"
  service:
    type: ClusterIP
    port: 3000

notification:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/notification-microservice
    tag: latest
    pullPolicy: IfNotPresent
  env:
    NODE_ENV: "production"
    KAFKA_BROKER: "mywebapp-kafka:9092"
  service:
    type: ClusterIP
    port: 3000

order:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/order-microservice
    tag: latest
    pullPolicy: IfNotPresent
  env:
    NODE_ENV: "production"
    KAFKA_BROKER: "mywebapp-kafka:9092"
  service:
    type: ClusterIP
    port: 3000
  probes:
    enabled: true
    initialDelaySeconds: 10
    livenessInitialDelaySeconds: 30

payment:
  replicas: 1
  containerPort: 3000
  image:
    repository: swistek/payment-microservice
    tag: latest
    pullPolicy: IfNotPresent
  env:
    NODE_ENV: "production"
    KAFKA_BROKER: "mywebapp-kafka:9092"
  service:
    type: ClusterIP
    port: 3000
  probes:
    enabled: true
    initialDelaySeconds: 10
    livenessInitialDelaySeconds: 30

products:
  replicas: 1
  containerPort: 50051
  image:
    repository: swistek/products-microservice
    tag: latest
    pullPolicy: Always
  env:
    NODE_ENV: "production"
  service:
    type: ClusterIP
    port: 50051
  probes:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 20

# ===== Bitnami Kafka (Kafka 4.0, KRaft domyślnie) =====

kafka:
  enabled: true
  image:
    repository: apache/kafka
    tag: latest
    pullPolicy: IfNotPresent
  containerPorts:
    - name: kafka
      containerPort: 9092
  env:
    KAFKA_CFG_PROCESS_ROLES: "broker,controller"
    KAFKA_CFG_NODE_ID: "1"
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
    KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
    KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://mywebapp-kafka:9092"
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
