apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "webapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.apiGateway.service.port | default 3000 }}
      targetPort: {{ .Values.apiGateway.containerPort | default 3000 }}
