# --------------------------------------------------------
# Kafka cluster definition (KRaft mode - Kafka 4.1.0)
# Works with Strimzi 0.41.0+
# --------------------------------------------------------
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dev
  namespace: kafka
spec:
  kafka:
    version: 4.1.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      # minimalne ustawienia dla single-node
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
# --------------------------------------------------------
# Combined NodePool (controller + broker in one pod)
# For small/dev environments
# --------------------------------------------------------
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dev-combined
  namespace: kafka
  labels:
    strimzi.io/cluster: dev
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
